name: ${project.name}
main: ${project.bukkit.main}
version: ${project.version} (git-${git.commit.id.abbrev})
api-version: ${project.paper.api}
author: ${project.author}
softdepend: [ProtocolLib, ViaVersion]
commands:
  autokiller:
    description: Main AutoKiller command.
    aliases: ak